//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidItalyAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidItalyAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between date.
        /// </summary>
        internal static string BetweenDate {
            get {
                return ResourceManager.GetString("BetweenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case per 100.000 inhabitants.
        /// </summary>
        internal static string CasePerinhabitants {
            get {
                return ResourceManager.GetString("CasePerinhabitants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        internal static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily cases.
        /// </summary>
        internal static string DailyCases {
            get {
                return ResourceManager.GetString("DailyCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily cases and swabs.
        /// </summary>
        internal static string DailyCasesSwabs {
            get {
                return ResourceManager.GetString("DailyCasesSwabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily deads.
        /// </summary>
        internal static string DailyDeads {
            get {
                return ResourceManager.GetString("DailyDeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily swabs.
        /// </summary>
        internal static string DailySwabs {
            get {
                return ResourceManager.GetString("DailySwabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deads.
        /// </summary>
        internal static string Deads {
            get {
                return ResourceManager.GetString("Deads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total deads ad range data.
        /// </summary>
        internal static string DeadsInRange {
            get {
                return ResourceManager.GetString("DeadsInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deads per 100.000 inhabitants.
        /// </summary>
        internal static string DeadsPerinhabitants {
            get {
                return ResourceManager.GetString("DeadsPerinhabitants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_folder_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_folder_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_refresh_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_refresh_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_save_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_save_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_settings_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_settings_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_synchronize_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_synchronize_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_undo_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_undo_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive Care.
        /// </summary>
        internal static string IntensiveCare {
            get {
                return ResourceManager.GetString("IntensiveCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New cases.
        /// </summary>
        internal static string NewCases {
            get {
                return ResourceManager.GetString("NewCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total new cases at range data.
        /// </summary>
        internal static string NewCasesInRange {
            get {
                return ResourceManager.GetString("NewCasesInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PopolazioneProvince {
            get {
                object obj = ResourceManager.GetObject("PopolazioneProvince", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PopolazioneRegioni {
            get {
                object obj = ResourceManager.GetObject("PopolazioneRegioni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship cases and swab.
        /// </summary>
        internal static string RelationshipCasesSwabs {
            get {
                return ResourceManager.GetString("RelationshipCasesSwabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swabs.
        /// </summary>
        internal static string Swabs {
            get {
                return ResourceManager.GetString("Swabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total swabs ad range data.
        /// </summary>
        internal static string SwabsInRange {
            get {
                return ResourceManager.GetString("SwabsInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swabs per 100.000 inhabitants.
        /// </summary>
        internal static string SwabsPerinhabitants {
            get {
                return ResourceManager.GetString("SwabsPerinhabitants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cases.
        /// </summary>
        internal static string TotalCases {
            get {
                return ResourceManager.GetString("TotalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly cases.
        /// </summary>
        internal static string WeeklyCases {
            get {
                return ResourceManager.GetString("WeeklyCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weekly cases and swabs.
        /// </summary>
        internal static string WeeklyCasesSwabs {
            get {
                return ResourceManager.GetString("WeeklyCasesSwabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weekly swabs.
        /// </summary>
        internal static string WeeklySwabs {
            get {
                return ResourceManager.GetString("WeeklySwabs", resourceCulture);
            }
        }
    }
}
